/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.sql.Connection;
import javax.swing.JFrame;
import DAO.AlunoDAO;
import DAO.ProvaDAO;
import DAO.QuestaoDAO;
import DAO.RelatorioDAO;
import DAO.AlternativaDAO;
import DAO.InstrutorDAO;
import DAO.RespostaAlunoDAO;
import GUI.CadastrarProva;
import GUI.TelaComVoltar;
import Modelo.Aluno;
import Modelo.Questao;
import Modelo.Relatorio;
import Modelo.Alternativa;
import Modelo.RespostaAluno;
import GUI.Login;
import GUI.Menu;
import GUI.EditarProvaCompleto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import Modelo.Prova;
import java.util.ArrayList;
import java.sql.DriverManager;
import java.sql.SQLException;
import Factory.ConnectionFactory;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
/**
 *
 * @author Eric
 */
public class MenuAluno extends javax.swing.JFrame {
    private Connection conn;
    private int id_aluno;
    private String nome_completo;

    public MenuAluno(Connection conn, int id_aluno, String nome_completo) {
        this.conn = conn;
        this.id_aluno = id_aluno;
        this.nome_completo = nome_completo;

        initComponents();
        
        

        // 1. Carrega o nome no JLabel
        lblNomeAluno.setText(nome_completo); // Ajuste para o nome do seu JLabel

        // 2. Carrega a foto de perfil do banco usando o id_aluno
        try {
    AlunoDAO alunoDAO = new AlunoDAO();
    Aluno aluno = alunoDAO.RecuperaPorId(id_aluno);
    if (aluno != null && aluno.getFotoPerfil() != null && !aluno.getFotoPerfil().isEmpty()) {
        int width = 120;
        int height = 120;
        ImageIcon icon = new ImageIcon(aluno.getFotoPerfil());
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lblFotoPerfilAluno.setIcon(new ImageIcon(img));
    } else {
        lblFotoPerfilAluno.setIcon(null);
    }
} catch (Exception e) {
    lblFotoPerfilAluno.setIcon(null);
}

        // SEU CÓDIGO DE CARREGAR PROVAS CONTINUA AQUI:
        try {
            ProvaDAO provaDAO = new ProvaDAO();
            List<Prova> listaProvas = provaDAO.getProvasDisponiveis(id_aluno);

            DefaultTableModel model = (DefaultTableModel) tabelaProvas.getModel();
            model.setRowCount(0); // Limpa a tabela

            for (Prova prova : listaProvas) {
                model.addRow(new Object[]{
                    prova.getid_prova(),
                    prova.getdescricao()
                    // Se quiser mostrar mais campos, adicione aqui
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar provas: " + e.getMessage());
        }
    }



    // Se já existir um construtor padrão, mantenha apenas o novo!

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVisualizarProvas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRealizarAvaliacao = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProvas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnSimuladorEstoque = new javax.swing.JButton();
        btnSimularNF = new javax.swing.JButton();
        btnSimularTransferencia = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnGestaoPedidos = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        btnRoteirizacao = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSelecionarFoto = new javax.swing.JButton();
        lblFotoPerfilAluno = new javax.swing.JLabel();
        lblNomeAluno = new javax.swing.JLabel();
        btnAcessibilidade = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        btnConfiguracoes = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logistica.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Menu Inicial do Aluno");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Screenshot_67.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(605, 605, 605)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 224, 189));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setText("Informações de Contato:");

        jLabel16.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 102));
        jLabel16.setText("Suporte Técnico: suporte@gmail.com");

        jLabel17.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 51, 102));
        jLabel17.setText("Telefone : (21) 99999-9999");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/prova1.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        btnVisualizarProvas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVisualizarProvas.setForeground(new java.awt.Color(0, 0, 102));
        btnVisualizarProvas.setText("Visualizar Provas ");
        btnVisualizarProvas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarProvasActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/10239997 (1).png"))); // NOI18N

        btnRealizarAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRealizarAvaliacao.setForeground(new java.awt.Color(0, 0, 102));
        btnRealizarAvaliacao.setText("Realizar Avaliação");
        btnRealizarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizarAvaliacaoActionPerformed(evt);
            }
        });

        tabelaProvas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProvas);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Avaliações Disponíveis");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lista-de-controle (1).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/taxa (1).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/estoque-pronto (1).png"))); // NOI18N

        btnSimuladorEstoque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimuladorEstoque.setForeground(new java.awt.Color(0, 0, 102));
        btnSimuladorEstoque.setText("Simular Estoque");
        btnSimuladorEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimuladorEstoqueActionPerformed(evt);
            }
        });

        btnSimularNF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimularNF.setForeground(new java.awt.Color(0, 0, 102));
        btnSimularNF.setText("Simular Nota Fiscal");
        btnSimularNF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularNFActionPerformed(evt);
            }
        });

        btnSimularTransferencia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSimularTransferencia.setForeground(new java.awt.Color(0, 0, 102));
        btnSimularTransferencia.setText("Simular Transferência de Estoque");
        btnSimularTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularTransferenciaActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/processamento-de-pedidos (1).png"))); // NOI18N

        btnGestaoPedidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGestaoPedidos.setForeground(new java.awt.Color(0, 0, 102));
        btnGestaoPedidos.setText("Gestão de Pedidos");
        btnGestaoPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestaoPedidosActionPerformed(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/rota (1).png"))); // NOI18N

        btnRoteirizacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRoteirizacao.setForeground(new java.awt.Color(0, 0, 102));
        btnRoteirizacao.setText("Roteirização");
        btnRoteirizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoteirizacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnVisualizarProvas)
                                .addComponent(jLabel4))
                            .addComponent(jLabel7))
                        .addGap(106, 106, 106)
                        .addComponent(jLabel13)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(300, 300, 300)
                                    .addComponent(btnSimuladorEstoque)
                                    .addGap(2, 2, 2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel8)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(btnRealizarAvaliacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimularNF)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnSimularTransferencia))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnGestaoPedidos)
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addGap(42, 42, 42))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(btnRoteirizacao))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 756, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(292, 292, 292))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSimularTransferencia)
                        .addGap(139, 139, 139)
                        .addComponent(jLabel14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jLabel4)
                                .addGap(20, 20, 20)
                                .addComponent(btnVisualizarProvas))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSimuladorEstoque)))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(10, 10, 10))
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRealizarAvaliacao)
                    .addComponent(btnSimularNF)
                    .addComponent(btnGestaoPedidos))
                .addGap(50, 50, 50)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(btnRoteirizacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(16, 16, 16))
        );

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/sair.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 102));
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<html> <br> Seja Bem-Vindo<br>  Aluno(a) : </html>");

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        btnSelecionarFoto.setText("Atualizar Foto");
        btnSelecionarFoto.setAlignmentX(0.5F);
        btnSelecionarFoto.setAlignmentY(0.0F);
        btnSelecionarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarFotoActionPerformed(evt);
            }
        });

        lblFotoPerfilAluno.setForeground(new java.awt.Color(242, 242, 242));
        lblFotoPerfilAluno.setAlignmentX(0.5F);
        lblFotoPerfilAluno.setAlignmentY(0.0F);

        lblNomeAluno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeAluno.setForeground(new java.awt.Color(242, 242, 242));
        lblNomeAluno.setAlignmentX(0.5F);
        lblNomeAluno.setAlignmentY(0.0F);

        btnAcessibilidade.setBackground(new java.awt.Color(204, 204, 204));
        btnAcessibilidade.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnAcessibilidade.setForeground(new java.awt.Color(0, 51, 102));
        btnAcessibilidade.setText("Acessibilidade");
        btnAcessibilidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcessibilidadeActionPerformed(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/acessibilidade3.png"))); // NOI18N

        btnConfiguracoes.setBackground(new java.awt.Color(204, 204, 204));
        btnConfiguracoes.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnConfiguracoes.setForeground(new java.awt.Color(0, 51, 102));
        btnConfiguracoes.setText("Configurações");
        btnConfiguracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracoesActionPerformed(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/conf3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblNomeAluno))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSelecionarFoto)
                            .addComponent(lblFotoPerfilAluno)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(btnAcessibilidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(btnConfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(lblNomeAluno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFotoPerfilAluno)
                .addGap(18, 18, 18)
                .addComponent(btnSelecionarFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnConfiguracoes)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAcessibilidade)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel12))
                .addGap(21, 21, 21))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 102));
        jLabel11.setText("Plataforma Educacional - Logística");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logistica.png"))); // NOI18N

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logistica.png"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logistica.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(61, 61, 61)
                .addComponent(jLabel22)
                .addGap(309, 309, 309)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(36, 36, 36))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel10)
                            .addComponent(jLabel22)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnVisualizarProvasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarProvasActionPerformed
        new VisualizarProvasAluno(conn, id_aluno, nome_completo).setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnVisualizarProvasActionPerformed

    private void btnRealizarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizarAvaliacaoActionPerformed
        int linhaSelecionada = tabelaProvas.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma prova!");
            return;
        }
        int id_prova = (int) tabelaProvas.getValueAt(linhaSelecionada, 0); // id_prova na coluna 0

        Connection conn = ConnectionFactory.getConnection();
        RealizarProvaAluno telaProva = new RealizarProvaAluno(conn, id_aluno, id_prova, nome_completo);
        telaProva.setVisible(true);
        this.dispose();
        // se quiser fechar o menu
    }//GEN-LAST:event_btnRealizarAvaliacaoActionPerformed

    private void btnSelecionarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarFotoActionPerformed
 JFileChooser fileChooser = new JFileChooser();
    int resultado = fileChooser.showOpenDialog(this);
    if (resultado == JFileChooser.APPROVE_OPTION) {
        File arquivo = fileChooser.getSelectedFile();
        String caminhoFoto = arquivo.getAbsolutePath();
        
        // Atualiza no banco
        AlunoDAO dao = new AlunoDAO();
        dao.atualizarFotoPerfil(id_aluno, caminhoFoto);

        // Exibe no JLabel usando tamanho fixo
        int width = 120; // ou outro valor que você padronizar
        int height = 120;
        ImageIcon icon = new ImageIcon(caminhoFoto);
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        lblFotoPerfilAluno.setIcon(new ImageIcon(img));

        JOptionPane.showMessageDialog(this, "Foto de perfil atualizada com sucesso!");
    }
  
    }//GEN-LAST:event_btnSelecionarFotoActionPerformed

    private void btnAcessibilidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcessibilidadeActionPerformed
        new gui.Acessibilidade(SwingUtilities.getWindowAncestor(this)).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAcessibilidadeActionPerformed

    private void btnConfiguracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracoesActionPerformed
Configurar telaConfig = new Configurar(conn,id_aluno, nome_completo);
    telaConfig.setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnConfiguracoesActionPerformed

    private void btnSimuladorEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimuladorEstoqueActionPerformed
new SimuladorEstoqueAluno().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnSimuladorEstoqueActionPerformed

    private void btnSimularNFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularNFActionPerformed
new RecebimentoNFAluno().setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularNFActionPerformed

    private void btnSimularTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularTransferenciaActionPerformed
new TransferenciaEstoqueAluno().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimularTransferenciaActionPerformed

    private void btnGestaoPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestaoPedidosActionPerformed
new TelaGestaoPedidos().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnGestaoPedidosActionPerformed

    private void btnRoteirizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoteirizacaoActionPerformed
new TelaRoteirizacao().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnRoteirizacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcessibilidade;
    private javax.swing.JButton btnConfiguracoes;
    private javax.swing.JButton btnGestaoPedidos;
    private javax.swing.JButton btnRealizarAvaliacao;
    private javax.swing.JButton btnRoteirizacao;
    private javax.swing.JButton btnSelecionarFoto;
    private javax.swing.JButton btnSimuladorEstoque;
    private javax.swing.JButton btnSimularNF;
    private javax.swing.JButton btnSimularTransferencia;
    private javax.swing.JButton btnVisualizarProvas;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFotoPerfilAluno;
    private javax.swing.JLabel lblNomeAluno;
    private javax.swing.JTable tabelaProvas;
    // End of variables declaration//GEN-END:variables
}
